# Generated by Django 2.2.19 on 2022-01-09 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20220109_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingListItem',
            new_name='ShoppingCart',
        ),
    ]
